import React, { Component } from 'react';

class About extends Component{
    render(){
        return(
            <div>
                <h1>This is about us.</h1>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget lacus egestas, fringilla erat a, interdum orci. Nam vitae ornare ipsum. Morbi tincidunt, neque eu vulputate dignissim, dui velit vehicula lacus, nec maximus enim ante eget leo. Nam ultricies ligula in feugiat tempor. Etiam faucibus, massa at aliquet ullamcorper, lorem ante laoreet risus, vel faucibus est tortor nec augue. Quisque posuere sem nulla, quis bibendum arcu tristique id. In rhoncus fermentum nibh varius venenatis. Phasellus luctus magna in lectus varius pellentesque. Suspendisse cursus, nunc non interdum hendrerit, ipsum felis porttitor nunc, et sodales sem mi vel enim. Morbi purus mi, facilisis non ultricies nec, facilisis et leo. Mauris dictum quam vel tellus aliquet, sed aliquam lectus tristique. Cras consectetur, erat ac tempus posuere, dolor mi tincidunt urna, at pellentesque mauris felis posuere risus.

Aenean at aliquet ex, in sagittis dolor. Sed congue nunc augue, sit amet sollicitudin lacus euismod eget. Mauris eleifend rhoncus quam, sed iaculis erat feugiat ut. Donec pulvinar dignissim metus, et convallis sem semper ac. In sodales lacus mattis, tristique tortor id, sagittis odio. Etiam at ultrices mi. Vivamus metus nisl, faucibus in imperdiet in, bibendum in elit. Morbi auctor dui sed felis euismod, quis consectetur purus rutrum. Aenean eu convallis ipsum. Curabitur commodo magna vitae sollicitudin luctus. Nam dignissim, magna vitae tristique dapibus, purus tellus accumsan quam, id fermentum augue ex sit amet ante. Aliquam erat volutpat. Morbi in rutrum eros.

Aenean suscipit urna et nulla finibus, quis tempus leo hendrerit. Mauris nisi velit, accumsan eget justo rhoncus, vehicula placerat lectus. Proin euismod nunc elit, vitae elementum quam facilisis at. Curabitur eget sem fermentum, feugiat tellus sit amet, sodales neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Aliquam egestas justo a ante aliquet sagittis. Nam sit amet consectetur sapien.

Nunc vitae tellus interdum, pharetra dolor quis, congue massa. Pellentesque molestie, diam et pretium dictum, lorem odio viverra magna, eu molestie mauris urna at ipsum. Proin interdum, tellus sed sollicitudin malesuada, sem sapien rhoncus libero, id dapibus magna est vel risus. Duis nisl tellus, porta nec sagittis sit amet, pulvinar cursus dui. Nam vestibulum pellentesque nulla. Curabitur gravida quis nibh quis malesuada. Nullam et augue enim. Nulla rhoncus justo ac turpis auctor, vel aliquam justo malesuada. Proin pellentesque magna et enim feugiat dictum. Nullam dictum iaculis orci, vel pellentesque arcu maximus quis. Etiam et enim vel eros rutrum posuere. Nullam eu velit diam.

Sed felis neque, sodales et nulla in, placerat dapibus urna. Ut dictum tellus velit, quis tempus tellus faucibus fringilla. Pellentesque leo velit, auctor vel sem id, feugiat faucibus odio. Fusce ultrices convallis ante eu convallis. Phasellus at ligula dolor. Phasellus eget ipsum sagittis, porta enim viverra, consequat quam. Aliquam erat volutpat. Suspendisse velit dolor, interdum vitae hendrerit nec, convallis eu tortor. Sed a lectus orci. Duis sollicitudin, nisl in gravida placerat, tellus justo mattis orci, vel posuere purus metus at magna. Nullam congue eleifend nunc, semper pharetra leo. Curabitur pharetra laoreet odio in rutrum. Nulla tempor tincidunt suscipit. Donec a posuere turpis. Donec tincidunt diam quis massa volutpat congue.

Proin vestibulum libero dui, in pulvinar purus viverra ut. Maecenas dictum pellentesque ultrices. Proin hendrerit mi ac sodales lobortis. Sed porta nisi vel tortor consequat, vel tincidunt nibh semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam efficitur elit turpis, sit amet dapibus ligula porta eu. Integer aliquet vel lorem id gravida. Etiam sit amet sodales nisi. Nunc efficitur imperdiet blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut dolor quam, semper in aliquet eget, faucibus ut massa.

Etiam erat ligula, fringilla consectetur rhoncus sit amet, tincidunt eget lorem. Nullam sit amet massa justo. Praesent rutrum consectetur erat ac blandit. Mauris a tincidunt ante. Maecenas mattis malesuada orci eu vulputate. Etiam rhoncus fermentum nisl eget accumsan. Praesent vehicula lorem enim, et rhoncus nisi finibus vitae. Sed non mi pellentesque purus mollis semper. Nunc tempor nibh in rutrum aliquam. Mauris interdum libero et dolor gravida, eget viverra nulla consectetur. Quisque tincidunt hendrerit purus ac rhoncus. Vestibulum molestie dictum sapien, eu auctor diam auctor eget. Integer interdum turpis ac facilisis euismod. Sed eu posuere mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse id orci ex.

Phasellus a sapien enim. Proin eget lobortis mauris, non vehicula dui. Integer et molestie tortor, vitae fringilla lorem. Fusce ullamcorper diam sem, nec consectetur purus rutrum nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent vulputate nec sapien et facilisis. Pellentesque ac tempor ex. Nam tristique id nisi at tempus. Duis ac scelerisque velit. Aenean vulputate rutrum quam a tristique. Nam lacinia ut arcu fermentum pharetra. Duis aliquet fringilla elit et aliquet.

Morbi sed condimentum lorem, ut lacinia quam. Vestibulum cursus interdum lacus vel interdum. Suspendisse ipsum est, accumsan scelerisque felis ut, fringilla dictum ante. Nullam tempus varius tortor at placerat. Vivamus pulvinar posuere metus in pulvinar. Nullam vitae nibh vitae risus aliquet efficitur eget ut nisl. Suspendisse ultrices posuere odio, eu semper est gravida sit amet. In tempus fermentum ex, in aliquam tellus suscipit vitae. Fusce in cursus turpis. Sed ornare nisl dui, vel faucibus dolor scelerisque et. Mauris in enim a diam gravida bibendum. Vestibulum volutpat iaculis viverra. Nulla tempus vehicula orci, quis blandit leo aliquet quis. Donec egestas felis varius, tincidunt sapien eu, lacinia justo. Ut elit ante, molestie eu vulputate id, posuere mollis felis.

Nulla mi lacus, tincidunt a volutpat in, interdum sed mi. Cras finibus diam sit amet tellus egestas, id lobortis est vulputate. Ut efficitur ultricies arcu, in semper purus. Ut condimentum venenatis iaculis. Integer eu odio diam. Phasellus nec blandit dolor. Donec cursus turpis
            </div>
        )
    }
}

export default About;
